### ISSUE TITLE
SpikeTrainArray doesn't have _restrict attribute

### ISSUE THREAD

**Issue by smevans19** [ssimonee/mind_2017#1]
https://nbviewer.jupyter.org/github/ssimonee/mind_2017/blob/master/Tutorials/SpikeDecoding/spike_decoding_python_SE10sept.ipynb

Object SpikeTrainArray should have _restrict attribute but doesn't giving Attribute Error. See In[9]

I inserted In[11] and In[10] in attempt to debug
Ran using Anaconda using Python 3.7.3 on Windows 10

**Comment by ckemere** [comment]
Can you try switching to the "develop" branch?

**Comment by ckemere** [comment]
Clarification - can you clone the repository (`git clone https://github.com/nelpy/nelpy`) and then run `git checkout develop` and `python setup.py develop`.

**Comment by ckemere** [comment]
Oh, and please `pip uninstall nelpy` first!

**Comment by smevans19** [comment]
Yep, that fixed it-- thanks so much!

**Comment by ckemere** [comment]
Awesome.

**Comment by ckemere** [comment]
Hey! I believe the bug has been fixed so that it should work with the master branch now. Do you mind checking?

**Comment by smevans19** [comment]
Hi-- sorry I didn't get to this yesterday! Still doesn't seem to work, I'm getting the same error as before.
I do want to confirm I switched to the master branch correctly (since I'm kind of new to python). I used pip uninstall and deleted nelpy from my computer entirely, then used pip install nelpy and ran the tutorial. (That's how I initially set up nelpy when I first ran the tutorial.)
I'm pushing the file to github and will send a link in a second.

**Comment by smevans19** [comment]
Here it is, see In[21]
https://nbviewer.jupyter.org/github/ssimonee/mind_2017/blob/master/Tutorials/SpikeDecoding/spike_decoding_python_SE13sept.ipynb

**Comment by ckemere** [comment]
I think this is because I exported the data using a previous version of nelpy. (Serialization of these classes so that they work through changes is something that needs serious work currently.) Give me a few minutes and I'll send a new version.

**Comment by ckemere** [comment]
Please see the updated data file here - https://www.dropbox.com/s/f34x7mnvfw3v2rp/FrankLabData.nel

**Comment by smevans19** [comment]
Got it, and I appreciate all the help. I'll let you know if there's any more issues. Thanks again!
